# 服务端口
server:
  port: 8301
# 服务名
spring:
  application:
    name: service-vod
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glkt_vod?characterEncoding=utf-8&useSSL=false
    username: root
    password: 1qaz!QAZ
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#腾讯云存储桶配置信息
#不同的服务器，地址不同
tencent:
  cos:
    file:
      region: ap-beijing
      secretId: AKIDrcBZcR4Vny3xfCWffWBbqOn2GNM9j9Rb
      secretKey: 1rZ6OUPHzV3b1IQQGtJZiojVAg074rW3
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketName: ggkt-atguigu-1319156449

mybatis-plus:
  mapper-locations: classpath:com/atguigu/ggkt/vod/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl