# 服务端口
server:
  port: 8333

# 服务名
spring:
  application:
    name: service-gateway

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true

  #service-vod模块配置
      routes[0]:
        #设置路由id
        id: service-vod
        #设置路由的uri
        uri: lb://service-vod
        #设置路由断言,代理servicerId为auth-service的/auth/路径
        predicates:
          - Path=/*/vod/**